services:
  eval:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - github_access=${GITHUB_ACCESS}
        - username=ppagonis
    restart: always
    environment:
      - FLASK_APP=run.py
  nginx:
    image: nginx:1.23.1-alpine
    restart: always
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - '80:80'
